# Site settings
title: Functional Mock-up Interface
email: contact@fmi-standard.org
description: > # this means to ignore newlines until "baseurl:"
  Functional Mock-up Interface (FMI) is a tool independent standard to support both model exchange and co-simulation of dynamic models using a combination of xml-files and compiled C-code (see overview in PDF or PPT format). The first version, FMI 1.0, was published in 2010, followed by FMI 2.0 in July 2014. The FMI development was initiated by Daimler AG with the goal to improve the exchange of simulation models between suppliers and OEMs
baseurl: "/fmi-standard.org" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
